{% set name = "scanapi" %}
{% set version = "2.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scanapi-{{ version }}.tar.gz
  sha256: 644633ca87c4a39ea29ad83c302c496a308a28096a5f8f7a4f91bcd28bc467fa

build:
  number: 0
  noarch: python
  entry_points:
    - scanapi = scanapi:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - appdirs >=1.4.4,<2.0.0
    - click ==7.1.2
    - curlify2 >=1.0.0,<2.0.0
    - jinja2 ==2.11.2
    - python >=3.6
    - pyyaml ==5.3.1
    - requests ==2.24.0
    - urllib3 >=1.25.10

test:
  imports:
    - scanapi
    - scanapi.evaluators
  commands:
    - pip check
    - scanapi --help
  requires:
    - pip

about:
  home: https://scanapi.dev/
  summary: Automated Testing and Documentation for your REST API
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/scanapi/scanapi
  description: |
    ScanAPI is a library for your API that provides automated integration
     testing and automated live documentation. Given an API specification
     written in YAML/JSON format, ScanAPI hits the specified endpoints, runs
     the test cases, and generates a detailed report of this execution—which
     can also be used as the API documentation itself. With almost no Python
     knowledge, the user can define endpoints to be hit, the expected behavior
     for each response and will receive a full real-time diagnostic report of
     the API.

extra:
  recipe-maintainers:
    - thewchan
