{% set name = "scanapi" %}
{% set version = "2.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scanapi-{{ version }}.tar.gz
  sha256: 39612f27e27b2e60ce7c36bb9ef2d722b4f6770ec0e83e71cf5729f5d25f4b9e

build:
  number: 0
  noarch: python
  entry_points:
    - scanapi = scanapi:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=1.0.9
    - poetry-dynamic-versioning
    - python >=3.7.13,<4.0.0
  run:

    - appdirs >=1.4.4
    - click ==8.0.3
    - curlify2 >=1.0.1
    - jinja2 ~=3.1.0
    - markupsafe ==2.0.1
    - python >=3.7.13,<4.0.0
    - pyyaml ~=6.0
    - requests >=2.26.0
    - rich ==12.1.0

test:
  imports:
    - scanapi
    - scanapi.evaluators
  commands:
    - scanapi --help
  requires:
    - pip

about:
  home: https://scanapi.dev/
  summary: Automated Testing and Documentation for your REST API
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/scanapi/scanapi
  description: |
    ScanAPI is a library for your API that provides automated integration
     testing and automated live documentation. Given an API specification
     written in YAML/JSON format, ScanAPI hits the specified endpoints, runs
     the test cases, and generates a detailed report of this execution—which
     can also be used as the API documentation itself. With almost no Python
     knowledge, the user can define endpoints to be hit, the expected behavior
     for each response and will receive a full real-time diagnostic report of
     the API.

extra:
  recipe-maintainers:
    - thewchan
