{% set name = "scanapi" %}
{% set version = "2.10.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scanapi-{{ version }}.tar.gz
  sha256: 13dcef565dea63ca4b3283a0c7c0692a1182312faefb1e75c79101db0353a2d0

build:
  number: 1
  noarch: python
  entry_points:
    - scanapi = scanapi:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry >=1.0.9
    - poetry-dynamic-versioning
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0.0
    - appdirs >=1.4.4,<2.0.0
    - curlify2 >=1.0.1,<2.0.0
    - markupsafe ==2.1.2
    - rich ==13.3.5
    - pyyaml ~=6.0.2
    - jinja2 ~=3.1.0
    - click >=8.1.3
    - httpx >=0.24.0,<0.25.0
    

test:
  imports:
    - scanapi
  commands:
    - pip check
    - scanapi --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://scanapi.dev/
  summary: Automated Testing and Documentation for your REST API
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/scanapi/scanapi
  description: |
    ScanAPI is a library for your API that provides automated integration
     testing and automated live documentation. Given an API specification
     written in YAML/JSON format, ScanAPI hits the specified endpoints, runs
     the test cases, and generates a detailed report of this execution—which
     can also be used as the API documentation itself. With almost no Python
     knowledge, the user can define endpoints to be hit, the expected behavior
     for each response and will receive a full real-time diagnostic report of
     the API.

extra:
  recipe-maintainers:
    - thewchan
