schema_version: 1

context:
  name: scanapi
  version: "2.13.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/scanapi-${{ version }}.tar.gz
  sha256: 3cc22abe4a5a2febb0980dd9e943fd9f061afb53e7781615fd6272626aa63796

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - scanapi = scanapi:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - wheel
  run:
    - python >=${{ python_min }}
    - appdirs >=1.4.4,<2.0.0
    - curlify2 >=1.0.1,<3.0.0
    - markupsafe ==3.0.3
    - rich ==14.2.0
    - pyyaml >=6.0.2,<6.1.0
    - jinja2 >=3.1.0,<3.2.0
    - click >=8.1.3
    - httpx >=0.27.0,<0.29.0
    - packaging >=24,<26
    - restrictedpython >=8.0,<9.0
    - prance >=25.4.8.0
    - openapi-spec-validator >=0.8.4

tests:
  - python:
      imports:
        - scanapi
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - scanapi --help

about:
  summary: Automated Testing and Documentation for your REST API
  license: MIT
  license_file: LICENSE
  description: |
    ScanAPI is a library for your API that provides automated integration
    testing and automated live documentation. Given an API specification
    written in YAML/JSON format, ScanAPI hits the specified endpoints, runs
    the test cases, and generates a detailed report of this execution—which
    can also be used as the API documentation itself. With almost no Python
    knowledge, the user can define endpoints to be hit, the expected behavior
    for each response and will receive a full real-time diagnostic report of
    the API.


  homepage: https://scanapi.dev/
  repository: https://github.com/scanapi/scanapi

extra:
  recipe-maintainers:
    - thewchan
